name: memex
channels:
    - blaze
    - memex
    - quasiben
    - brittainhard
    - bokeh
dependencies:
    - elasticsearch=1.6.0
    - tika-rest-server=1.9.0
    - kibana
    - bokeh=0.10.0
    # certifi needed by bokeh server!
    - certifi
    - blaze=0.8.2
    - python=2.7.8
    - nutch-python>=1.11
    - elasticnutch>=1.11
    - ache=0.3.0
    - django=1.7.3
    - gunicorn
    - pytest
    - pip
    - jinja2
    - redis-py
    - nodejs
    - pip:
        - tld
        - tika==1.8.7
        - selenium
        - coverage
        - pytest-cov
        - pytest-django
        - pytest-ordering
        - django-crispy-forms
        - django-debug-toolbar
        - coveralls
        - sphinx-rtd-theme
        - celery
        - elasticsearch
        - supervisor
        - djangorestframework
        - django-filter
