name: memex
channels:
    - blaze
    - memex
    - quasiben
dependencies:
    - bokeh=0.7.0
    - blaze=0.7.0
    - python=2.7.8
    - nutch
    - ache=0.1.0
    - django=1.7.3
    - gunicorn
    - pytest
    - pip
    - pip:
        - tld
        - selenium
        - coverage
        - pytest-cov
        - pytest-django
        - pytest-ordering
        - django-crispy-forms
        - coveralls
