name: memex-explorer
channels:
  - blaze
  - quasiben
  - memex
dependencies:
  - blaze=0.6.7
  - Flask=0.10.1
  - bokeh=0.7
  - nutch
  - ache=0.1.0
  - pip
  - pip:
    - Flask-WTF==0.8.2
    - flask-mail==0.9.1
    - flask-sqlalchemy==2.0
    - flask-migrate
    - tld==0.7.2
    - WTForms==2.0.1
    - supervisor==3.0
    - unicodecsv==0.9.4
    - webhelpers==1.3